name: Eddies
channels:
  - conda-forge/label/cf202003
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - basemap=1.2.2
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - catboost=1.0.3
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=3.470
  - chardet=4.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=36.0.0
  - curl=7.78.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.12.0
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fiona=1.8.20
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.11.0
  - freexl=1.0.6
  - gdal=3.3.2
  - geojson=2.5.0
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - gmaps=0.9.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icc_rt=2019.0.0
  - icu=68.2
  - imageio=2.8.0
  - importlib-metadata=4.8.2
  - importlib_resources=5.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.4.2
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.0
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.2.1
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libclang=11.1.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libffi=3.4.2
  - libgdal=3.3.2
  - libglib=2.68.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.4
  - notebook=6.4.6
  - numba=0.54.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandas=1.2.1
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.2
  - pixman=0.40.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.0.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pywavelets=1.1.1
  - pywin32=301
  - pyzmq=22.3.0
  - qt=5.12.9
  - rtree=0.9.7
  - scikit-image=0.16.2
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shap=0.34.0
  - sip=4.19.13
  - six=1.16.0
  - slicer=0.0.7
  - sqlite=3.36.0
  - termcolor=1.1.0
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xyzservices=2021.11.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - affine==2.3.0
    - appdirs==1.4.4
    - asciitree==0.3.3
    - beautifulsoup4==4.10.0
    - bokeh==2.4.1
    - bottleneck==1.3.2
    - cftime==1.5.1.1
    - charset-normalizer==2.0.7
    - dask==2021.10.0
    - distributed==2021.10.0
    - docopt==0.6.2
    - eccodes==1.3.3
    - fasteners==0.16.3
    - findlibs==0.0.2
    - fsspec==2021.10.1
    - h5netcdf==0.11.0
    - h5py==3.5.0
    - heapdict==1.0.1
    - idna==3.3
    - jinja2==3.0.2
    - llvmlite==0.37.0
    - locket==0.2.1
    - msgpack==1.0.2
    - nc-time-axis==1.4.0
    - netcdf4==1.5.7
    - numbagg==0.2.1
    - numcodecs==0.9.1
    - packaging==21.2
    - partd==1.2.0
    - plotly==5.4.0
    - psutil==5.8.0
    - pycparser==2.20
    - pygmaps-enhanced==0.2.0
    - pyparsing==2.4.7
    - python-graphviz==0.18.2
    - pywinpty==1.1.6
    - pyyaml==6.0
    - requests==2.26.0
    - seaborn==0.11.2
    - shapely==1.8.0
    - snuggs==1.4.7
    - sortedcontainers==2.4.0
    - soupsieve==2.2.1
    - tblib==1.7.0
    - tenacity==8.0.1
    - terminado==0.12.1
    - toolz==0.11.1
    - webencodings==0.5.1
    - webob==1.8.7
    - zarr==2.10.2
    - zict==2.0.0
